version: "1"
rules:
  - base: lme
    upstream: LmeSzinc:master
    mergeMethod: merge
    mergeUnstable: true
  - base: GG
    upstream: Zuosizhu:master
    mergeMethod: merge
    mergeUnstable: true
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict": true